Develop Latvian translations
go-playground/validator pull request #1005
Opened 2022-09-29 17:54 UTC by gatisr

## Fixes Or Enhances

**Make sure that you've checked the boxes below before you submit PR:**
- [x ] Tests exist or have been written that cover this particular change.

@go-playground/validator-maintainers

2022-10-05 08:07 UTC, zemzale requested changes
Looks good. Just a few changes that should be made.

2022-10-05 08:07 UTC, zemzale commented on translations/lv/lv.go
> +			translation: "{0} jāsatur derīga numeric vērtība",
This probably should be `jāsatur tikai cipari`

2022-10-05 08:07 UTC, zemzale commented on translations/lv/lv.go
> +			translation: "{0} jāsatur derīgs numurs",
This probably should be `jāsatur dreīgs skaitlis`

2022-10-05 08:07 UTC, zemzale commented on translations/lv/lv.go
> +			translation: "{0} does not match postcode format of {1} country",
Missed translation. Suggesting something like 
`neatbilst {1} valsts pasta indeksa formātam`

2022-10-05 08:07 UTC, zemzale commented on translations/lv/lv.go
> +			translation: "{0} does not match postcode format of country in {1} field",
Same as the other post-code translation.

2022-10-05 09:25 UTC, zemzale approved these changes
Looks good now. @deankarn This can be merged if there are no problems with the implementation, but the translations look good.

2023-03-19 20:05 UTC, deankarn approved these changes

2023-03-19 20:05 UTC, merged