fat: URN RFC 8141
go-playground/validator pull request #1224
Opened 2024-02-12 12:28 UTC by leodido

## Fixes Or Enhances

Fixes #1223

**Make sure that you've checked the boxes below before you submit PR:**
- [x] Tests exist or have been written that cover this particular change.

@go-playground/validator-maintainers

2024-06-01 14:57 UTC, deankarn commented on baked_in.go
> +		"urn":                           isUrnRFC8141, // RFC 8141
One requested change to match the rfc
```suggestion
		"urn_rfc8141":                           isUrnRFC8141, // RFC 8141
```

2025-03-08 01:24 UTC, nodivbyzero commented
LGTM

@leodido  Could you update the README.md with `urn_rfc8141`?

2025-04-07 14:56 UTC, nodivbyzero approved these changes

2026-07-16 13:21 UTC, leodido commented
Ping

2026-07-17 03:24 UTC, nodivbyzero commented on baked_in.go
> +		str := field.String()
If str == "", we should return false.

2026-07-17 03:24 UTC, nodivbyzero requested changes

2026-07-17 03:35 UTC, nodivbyzero commented
@leodido 
I reviewed this PR again. One minor issue and it's good to go.

2026-07-17 07:29 UTC, leodido commented on baked_in.go
> +		str := field.String()
Empty input is already rejected by go-urn in RFC 8141 mode, but making that contract explicit here is reasonable. I’ll add the early return and a corresponding test case.

2026-07-17 13:12 UTC, leodido commented
@nodivbyzero done! PTAL

2026-07-17 17:27 UTC, nodivbyzero approved these changes

2026-07-17 17:28 UTC, merged