Add Korean
go-playground/validator pull request #1338
Opened 2024-12-03 03:11 UTC by jkh0kr

## Fixes Or Enhances

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] Tests exist or have been written that cover this particular change.

@go-playground/validator-maintainers

2025-01-14 07:09 UTC, JunBumHan commented
coverage만 어떻게 해결해보면 될 것 같은데요 ㅠㅠ

2025-02-24 18:37 UTC, nodivbyzero requested changes

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("len-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("len-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("min-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
same here. Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("min-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
same here. please delete

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("max-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
delete

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("max-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
delete

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("ne-items-item", "{0}개", locales.PluralRuleOne, false); err != nil {
delete

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("lt-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("lt-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("lte-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("lte-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gt-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gte-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-24 18:37 UTC, nodivbyzero commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gte-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
Please delete any commented-out code that is not in use.

2025-02-26 01:07 UTC, jkh0kr commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gte-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
Comment removed.

2025-02-26 01:08 UTC, jkh0kr commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gte-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
> Please delete any commented-out code that is not in use.

Comment removed.

2025-02-26 01:08 UTC, jkh0kr commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gte-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
> Please delete any commented-out code that is not in use.

Comment removed.

2025-02-26 01:08 UTC, jkh0kr commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("gt-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
> Please delete any commented-out code that is not in use.

Comment removed.

2025-02-26 01:08 UTC, jkh0kr commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("lte-items-item", "{0}개의 항목", locales.PluralRuleOne, false); err != nil {
> Please delete any commented-out code that is not in use.

Comment removed.

2025-02-26 01:08 UTC, jkh0kr commented on translations/ko/ko.go
> +				// if err = ut.AddCardinal("lte-string-character", "{0}자", locales.PluralRuleOne, false); err != nil {
> Please delete any commented-out code that is not in use.

Comment removed.

2025-02-26 01:08 UTC, jkh0kr commented
All Comment removed.~

2025-02-26 22:45 UTC, nodivbyzero approved these changes

2025-02-27 22:18 UTC, merged